@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2NTIzMTIxNjJ9.F4uSsQYaacGjxGHc40Esi08v6JPBl51-7IEpRB9jwwY

### Users Index
GET http://localhost:3000/users.json

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
"email": "DallasDork",
"username": "ImMad@test.com",
"password": "password",
"password_confirmation": "password"
}

### Users Show
GET http://localhost:3000/users/2.json

### Users Update
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{
"email": "Update email",
"password_digest": "password",
"username": "Update Username"
}

### users Destroy
DELETE http://localhost:3000/users/3.json


### locations Index
GET http://localhost:3000/locations.json

### locations Create
POST http://localhost:3000/locations.json
Content-Type: application/json

{
"state": "Test state",
"state_bird": "test password",
"location_comments": "test location_comments"
}

### locations Show
GET http://localhost:3000/locations/1.json

### locations Update
PATCH http://localhost:3000/locations/50.json
Content-Type: application/json

{
"state": "WY",
"state_bird": "Western Meadowlark",
"location_comments": "https://statesymbolsusa.org/sites/statesymbolsusa.org/files/primary-images/FlagWyomingstateFlag.jpg"
}

### locations Destroy
DELETE http://localhost:3000/locations/53.json


### birds Index
GET http://localhost:3000/birds.json

### birds Create
POST http://localhost:3000/birds.json
Content-Type: application/json

{
"c_name": "Test",
"s_name": "test",
"image_url": "test",
"post_count": 0,
"description": "",
"background_url": ""
}

### birds Show
GET http://localhost:3000/birds/32.json

### birds Update
PATCH http://localhost:3000/birds/50.json
Content-Type: application/json

{
"c_name": "Yellow-crowned Night-Heron",
"s_name": "Nyctanassa violacea",
"image_url": "https://bloximages.newyork1.vip.townnews.com/bayjournal.com/content/tncms/assets/v3/editorial/b/c8/bc87fe35-2a3d-5434-bbbe-abb19acf9760/5db1dd5c3bc74.image.jpg?resize=392%2C600",
"post_count": 0,
"description": "More solitary and often more secretive than the Black-crowned Night-Heron, the Yellow-crowned is still quite common in parts of the southeast. Particularly in coastal regions, often feeds by day as well as by night. Its stout bill seems to be an adaptation for feeding on hard-shelled crustaceans -- it is called 'crab-eater' in some locales. The species was introduced into Bermuda in a successful attempt to bring land crabs under control there.",
"background_url": "https://www.birdorable.com/img/bird/m/black-crowned-night-heron.png"
}

### birds Destroy
DELETE http://localhost:3000/birds/60.json


### Comments Index
GET http://localhost:3000/comments.json

### Comments Create
POST http://localhost:3000/comments.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"bird_id": 13,
"location_id": 13,
"comment_text": "Test Comment",
"lat": 41.93837,
"long": -82.66432
}

### Comments Show
GET http://localhost:3000/comments/1.json

### Comments Update
PATCH http://localhost:3000/comments/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json


{
"bird_id": 32,
"location_id": 42,
"user_id": 1,
"comment_text": "teste Saw a Bald eagle getting swarmed by ospreys mid river in april 2022, the coordinates are to a bluff at melton hill park in hardin valley, east TN",
"lat": 35.94680,
"long": -84.23727
}

### comments Destroy
DELETE http://localhost:3000/comments/12.json
Authorization: Bearer {{jwt}}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "Chicagocubsfan@test.com",
  "password": "password"
}

### Requests Index
GET http://localhost:3000/requests.json

### Requests Create
POST http://localhost:3000/requests.json
Content-Type: application/json

{
"new_bird": "Velociraptor"
}

### requests Show
GET http://localhost:3000/requests/1.json

### requests Update
PATCH http://localhost:3000/requests/1.json
Content-Type: application/json

{
"new_bird": "pigeon"
}

### requests Destroy
DELETE http://localhost:3000/locations/53.json
