@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxOCwiZXhwIjoxNjUyODE0NjA0fQ.ojSXMVR3SEt1MkdMedxyBYWx12CQ7Plom2Upc-dev3U

### Users Index
GET http://localhost:3000/users.json

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
"email": "DallasDork",
"username": "ImMad@test.com",
"password": "password",
"password_confirmation": "password"
}

### Users Show
GET http://localhost:3000/users/2.json

### Users Update
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{
"email": "Update email",
"password_digest": "password",
"username": "Update Username"
}

### users Destroy
DELETE http://localhost:3000/users/3.json


### locations Index
GET http://localhost:3000/locations.json

### locations Create
POST http://localhost:3000/locations.json
Content-Type: application/json

{
"state": "Test state",
"state_bird": "test password",
"location_comments": "test location_comments"
}

### locations Show
GET http://localhost:3000/locations/1.json

### locations Update
PATCH http://localhost:3000/locations/50.json
Content-Type: application/json

{
"state": "WY",
"state_bird": "Western Meadowlark",
"location_comments": "https://statesymbolsusa.org/sites/statesymbolsusa.org/files/primary-images/FlagWyomingstateFlag.jpg"
}

### locations Destroy
DELETE http://localhost:3000/locations/53.json


### birds Index
GET http://localhost:3000/birds.json

### birds Create
POST http://localhost:3000/birds.json
Content-Type: application/json

{
"c_name": "Test",
"s_name": "test",
"image_url": "test",
"post_count": 0,
"description": "",
"background_url": ""
}

### birds Show
GET http://localhost:3000/birds/32.json

### birds Update
PATCH http://localhost:3000/birds/7.json
Content-Type: application/json

{
"c_name": "American Robin",
"s_name": "Turdus migratorius",
"image_url": "https://www.allaboutbirds.org/guide/assets/photo/303441781-480px.jpg",
"post_count": 0,
"description": "A very familiar bird over most of North America, running and hopping on lawns with upright stance, often nesting on porches and windowsills. The Robin's rich caroling is among the earliest bird songs heard at dawn in spring and summer, often beginning just before first light. In fall and winter, robins may gather by the hundreds in roaming flocks, concentrating at sources of food.",
"background_url": "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2021-08/210810-robin-dc-comics-ac-420p-631a32.jpg"
}

### birds Destroy
DELETE http://localhost:3000/birds/60.json


### Comments Index
GET http://localhost:3000/comments.json

### Comments Create
POST http://localhost:3000/comments.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"bird_id": 13,
"location_id": 13,
"comment_text": "Test Comment",
"lat": 41.93837,
"long": -82.66432
}

### Comments Show
GET http://localhost:3000/comments/1.json

### Comments Update
PATCH http://localhost:3000/comments/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json


{
"bird_id": 32,
"location_id": 42,
"user_id": 1,
"comment_text": "teste Saw a Bald eagle getting swarmed by ospreys mid river in april 2022, the coordinates are to a bluff at melton hill park in hardin valley, east TN",
"lat": 35.94680,
"long": -84.23727
}

### comments Destroy
DELETE http://localhost:3000/comments/12.json
Authorization: Bearer {{jwt}}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "TheBigHurt@test.com",
  "password": "password"
}

### Requests Index
GET http://localhost:3000/requests.json

### Requests Create
POST http://localhost:3000/requests.json
Content-Type: application/json

{
"new_bird": "Velociraptor"
}

### requests Show
GET http://localhost:3000/requests/1.json

### requests Update
PATCH http://localhost:3000/requests/1.json
Content-Type: application/json

{
"new_bird": "pigeon"
}

### requests Destroy
DELETE http://localhost:3000/locations/53.json


### Migrations Index
GET http://localhost:3000/migs

